apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-ads-controller
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: google-ads-controller
  template:
    metadata:
      labels:
        run: google-ads-controller
    spec:
      containers:
        - name: google-ads-controller
          image: adomate/google-ads-controller:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          envFrom:
            - secretRef:
                name: gac-secrets
      imagePullSecrets:
        - name: dockerhub-credentials
