apiVersion: apps/v1
kind: Deployment
metadata:
    name: adomate
spec:
    replicas: 2
    revisionHistoryLimit: 2
    selector:
        matchLabels:
            run: adomate
    template:
        metadata:
            labels:
                run: adomate
        spec:
            containers:
                - name: adomate
                  image: raajpatel229/adomate-frontend:latest
                  ports:
                      - containerPort: 80
                  imagePullPolicy: Always
                  resources:
                      requests:
                          cpu: 50m
                          memory: 256Mi
                      limits:
                          cpu: 100m
                          memory: 512Mi