apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: raajpatel229/adomate-frontend
  newTag: 1fdcd1f599298c1d1fcb5a26011c24260a7a083e
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
