apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: raajpatel229/adomate-frontend
  newTag: 9e102d4c0ef815e42377392484ffab5bceeda7ae
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
