apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: raajpatel229/adomate-frontend
  newTag: 64f0cd696d58b5f224f9e66d29d67aa62a09e6c1
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
