apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: raajpatel229/adomate-frontend
  newTag: 9aa0803ce4b3a30b63f5873e975f95707ec474ab
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
