apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: raajpatel229/adomate-frontend
  newTag: 608cd3466885a88bd11d8b0eb489a4317f7c1964
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
