apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: adomate/api
  newName: adomate/api
  newTag: 43a85c6ea9445cf93e9d29bc5006d022d15757a4
- name: adomate/dashboard
  newName: adomate/dashboard
  newTag: dev-507aa27e507b2357973108c2644531962056a5f0
- name: adomate/discord-bot
  newName: adomate/discord-bot
  newTag: 0951646cb45439dbc3eefbb2ad23777a03300b7a
- name: adomate/google-ads-controller
  newName: adomate/google-ads-controller
  newTag: f98868a24ed07bd63735c0d5792c55779de2ef33
- name: adomate/mail-server
  newName: adomate/mail-server
  newTag: e051f1ef4140ccad06347dafc12a3b5aec8cdbe3
- name: adomate/site-analyzer
  newName: adomate/site-analyzer
  newTag: eec431f5748a6daada9d7a6817d5ca8763296665
- name: raajpatel229/adomate-frontend
  newName: raajpatel229/adomate-frontend
  newTag: dev-cca7fb68fbef2a14361fc01eb40a31ab14a8ac35
patchesStrategicMerge:
- api/merge/certificate.yaml
- api/merge/ingress.yaml
- frontend/merge/certificate.yaml
- frontend/merge/ingress.yaml
- dashboard/merge/certificate.yaml
- dashboard/merge/ingress.yaml
