apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: adomate/api
  newName: adomate/api
  newTag: 578a144e76ba7c80ee9256750eb81c32d5fced68
- name: adomate/dashboard
  newName: adomate/dashboard
  newTag: dev-90ffe7bcff50e85f0321ff2dc59b6f7c6cb00e58
- name: adomate/discord-bot
  newName: adomate/discord-bot
  newTag: 0951646cb45439dbc3eefbb2ad23777a03300b7a
- name: adomate/google-ads-controller
  newName: adomate/google-ads-controller
  newTag: f98868a24ed07bd63735c0d5792c55779de2ef33
- name: adomate/mail-server
  newName: adomate/mail-server
  newTag: e051f1ef4140ccad06347dafc12a3b5aec8cdbe3
- name: adomate/site-analyzer
  newName: adomate/site-analyzer
  newTag: eec431f5748a6daada9d7a6817d5ca8763296665
- name: raajpatel229/adomate-frontend
  newName: raajpatel229/adomate-frontend
  newTag: dev-d021b6b9815efc2ab0150a9fb35a8d5a8092fe41
patchesStrategicMerge:
- api/merge/certificate.yaml
- api/merge/ingress.yaml
- frontend/merge/certificate.yaml
- frontend/merge/ingress.yaml
- dashboard/merge/certificate.yaml
- dashboard/merge/ingress.yaml
