apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: adomate/api
  newName: adomate/api
  newTag: c87b628abddc346480c56991e50e29d59a296d51
- name: adomate/dashboard
  newName: adomate/dashboard
  newTag: f26f529a23815ac128678f99f45dcfd0207d3d6d
- name: raajpatel229/adomate-frontend
  newName: raajpatel229/adomate-frontend
  newTag: 7c2d02e961f7428268b40edd6124ff5249bba705
patchesStrategicMerge:
- api/merge/certificate.yaml
- api/merge/ingress.yaml
- frontend/merge/certificate.yaml
- frontend/merge/ingress.yaml
- dashboard/merge/certificate.yaml
- dashboard/merge/ingress.yaml
