apiVersion: apps/v1
kind: Deployment
metadata:
    name: mysql
spec:
    replicas: 2
    revisionHistoryLimit: 2
    selector:
        matchLabels:
            app: mysql
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxUnavailable: 1
    template:
        metadata:
            labels:
                app: mysql
        spec:
            containers:
                - name: mysql
                  image: mysql:8
                  ports:
                      - containerPort: 3306
                  envFrom:
                      - configMapRef:
                            name: mysql-config
                  volumeMounts:
                      - name: mysql-data
                        mountPath: /var/lib/mysql
                  livenessProbe:
                      tcpSocket:
                          port: 3306
                      initialDelaySeconds: 15
                      periodSeconds: 10
                  readinessProbe:
                      tcpSocket:
                          port: 3306
                      initialDelaySeconds: 5
                      periodSeconds: 10
                  resources:
                      requests:
                          cpu: 250m
                          memory: 512Mi
                      limits:
                          cpu: 500m
                          memory: 1024Mi
            volumes:
                - name: mysql-data
                  persistentVolumeClaim:
                      claimName: mysql-pv-claim