apiVersion: v1
kind: ConfigMap
metadata:
    name: rabbitmq-config
    namespace: rabbitmq
data:
    rabbitmq.conf: |-
          log.file.level = debug
          log.console = true
          log.console.level = debug
