apiVersion: apps/v1
kind: Deployment
metadata:
    name: rabbitmq
spec:
    replicas: 1
    selector:
        matchLabels:
            run: rabbitmq
    template:
        metadata:
            labels:
                run: rabbitmq
        spec:
            containers:
                - name: rabbitmq
                  image: rabbitmq:3
                  ports:
                      - containerPort: 5672
                  imagePullPolicy: Always