apiVersion: v1
kind: PersistentVolume
metadata:
    name: rabbitmq-pv-volume
    namespace: rabbitmq
spec:
    accessModes:
        - ReadWriteOnce
    capacity:
        storage: 10Gi
    hostPath:
        path: /mnt/data/rabbitmq
    storageClassName: manual
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: rabbitmq-pv-claim
    namespace: rabbitmq
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 10Gi
    storageClassName: manual
    selector:
        matchLabels:
            app: rabbitmq
