apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
    - name: raajpatel229/adomate-frontend
      newTag: latest
resources:
    - deployment.yaml
  - ingress.yaml
  - service.yaml