apiVersion: apps/v1
kind: Deployment
metadata:
    name: api
spec:
    replicas: 2
    selector:
        matchLabels:
            app: api
    template:
        metadata:
            labels:
                app: api
        spec:
            initContainers:
                - name: config
                  image: raajpatel229/adomate-api:latest
                  imagePullPolicy: Always
                  env:
                      - name: CONFIGMAP_PATH
                        value: /tmp/config-map/config.yaml
        - name: DEFAULT_CONFIGMAP
          value: /app/config.yaml.default
        - name: ENV_PATH
          value: /app
        - name: CONFIG
          value: /etc/api/config.yaml
                  envFrom:
                      - secretRef:
                            name: api-secrets
                            optional: false
        - secretRef:
              name: discord-webhooks
                  command:
                      - /bin/bash
        - -c
        - |-
          /bin/bash /app/init.sh
          cat /etc/zdv-api/config.yaml
                  volumeMounts:
                      - name: config
                        mountPath: /etc/zdv-api
        - name: config-map
          mountPath: /tmp/config-map
            containers:
                - name: api
                  image: raajpatel229/adomate-api:latest
                  imagePullPolicy: Always
                  ports:
                      - containerPort: 3000
                        protocol: TCP
                  readinessProbe:
                      failureThreshold: 3
                      httpGet:
                          path: /v1
                          port: 3000
                          scheme: HTTP
                      initialDelaySeconds: 10
                      periodSeconds: 10
                      successThreshold: 1
                      timeoutSeconds: 1
                  livenessProbe:
                      failureThreshold: 3
                      httpGet:
                          path: /v1
                          port: 3000
                          scheme: HTTP
                      initialDelaySeconds: 10
                      periodSeconds: 10
                      successThreshold: 1
                      timeoutSeconds: 1
                  command: ["/app/api"]
                  args:
                      - server
          - --config
          - /etc/api/config.yaml
                  volumeMounts:
                      - name: config
                        mountPath: /etc/api
                  resources:
                      requests:
                          cpu: 200m #200 millicpu AKA 0.2vCPU
                          memory: 50Mi
                      limits:
                          cpu: 1000m #1000 millicpu AKA 1vCPU
                          memory: 512Mi
            volumes:
                - name: config
                  emptyDir: {}
      - name: config-map
        configMap:
            name: api-config