apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: adomate/api
  newTag: c69dc198ded9dac9882052c76edf3f890b5461f7
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
