apiVersion: v1
kind: Service
metadata:
  name: google-ads-controller
  labels:
    run: google-ads-controller
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    run: google-ads-controller
