apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-adomate-ai-tls
spec:
  dnsNames:
    - api.adomate.ai
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: api-adomate-ai-tls