apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: adomate/api:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          envFrom:
            - secretRef:
                name: api-secrets
      imagePullSecrets:
        - name: dockerhub-credentials