apiVersion: v1
kind: Service
metadata:
  labels:
    run: site-analyzer
  name: site-analyzer
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    run: site-analyzer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: site-analyzer
  namespace: site-analyzer
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: site-analyzer
  template:
    metadata:
      labels:
        run: site-analyzer
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: site-analyzer-secrets
        image: adomate/site-analyzer:94d85c757230b3b024b9e66ec3e5efad2cb42d3b
        imagePullPolicy: Always
        name: site-analyzer
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 50Mi
      imagePullSecrets:
      - name: dockerhub-credentials
