apiVersion: apps/v1
kind: Deployment
metadata:
    name: mail-server
    namespace: mail-server
spec:
    replicas: 1
    revisionHistoryLimit: 2
    selector:
        matchLabels:
            run: mail-server
    template:
        metadata:
            labels:
                run: mail-server
        spec:
            containers:
                - name: mail-server
                  image: adomate/mail-server:latest
                  ports:
                      - containerPort: 3000
                  imagePullPolicy: Always
                  resources:
                      requests:
                          cpu: 50m #50 millicpu AKA 0.05vCPU
                          memory: 50Mi
                      limits:
                          cpu: 150m #150 millicpu AKA 0.15vCPU
                          memory: 256Mi
                  envFrom:
                  - secretRef:
                      name: mail-server-secrets
            imagePullSecrets:
            - name: dockerhub-credentials
