apiVersion: v1
kind: Service
metadata:
    name: mail-server
    labels:
        app: mail-server
spec:
    ports:
        - port: 3000
          targetPort: 3000
    selector:
        app: mail-server