apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-server
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: mail-server
  template:
    metadata:
      labels:
        run: mail-server
    spec:
      containers:
        - name: mail-server
          image: adomate/mail-server:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 25m
              memory: 50Mi
            limits:
              cpu: 150m
              memory: 256Mi
          envFrom:
            - secretRef:
                name: mail-server-secrets
      imagePullSecrets:
        - name: dockerhub-credentials