apiVersion: v1
kind: Service
metadata:
  labels:
    run: api-dev
  name: api-dev
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    run: api-dev
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-dev
  namespace: api-dev
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      run: api-dev
  template:
    metadata:
      labels:
        run: api-dev
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: api-secrets
        image: adomate/api:5579540e69306dca33409ede1cfc412129b0ecae
        imagePullPolicy: Always
        name: api-dev
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 50Mi
      imagePullSecrets:
      - name: dockerhub-credentials
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  name: api-dev-ingress
  namespace: api-dev
spec:
  rules:
  - host: api.dev.adomate.ai
    http:
      paths:
      - backend:
          service:
            name: api-dev
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - api.dev.adomate.ai
    secretName: frontend-tls
