rabbitmq:
  auth:
    username: adomate
    existingPasswordSecret: passwords
  primary:
    resources:
      requests:
        memory: 1500Mi
        cpu: 250m
      limits:
        memory: 3000Mi
        cpu: 1000m
