apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: www-adomate-ai-tls
spec:
  dnsNames:
    - www.adomate.ai
    - adomate.ai
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt
  secretName: www-adomate-ai-tls