apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: adomate/api
  newName: adomate/api
  newTag: a7ed6c83a0ebca86afb9bff4a12a2294e8215fa1
- name: adomate/dashboard
  newName: adomate/dashboard
  newTag: 78b5c2424f1646804b2d1168b93564a397a5049b
- name: adomate/discord-bot
  newName: adomate/discord-bot
  newTag: 0ac48c6c334b9c48894b35ff807e2611c0e93866
- name: adomate/google-ads-controller
  newName: adomate/google-ads-controller
  newTag: f98868a24ed07bd63735c0d5792c55779de2ef33
- name: adomate/mail-server
  newName: adomate/mail-server
  newTag: e051f1ef4140ccad06347dafc12a3b5aec8cdbe3
- name: adomate/site-analyzer
  newName: adomate/site-analyzer
  newTag: eec431f5748a6daada9d7a6817d5ca8763296665
- name: raajpatel229/adomate-frontend
  newName: raajpatel229/adomate-frontend
  newTag: b70f84f5285aed85c009f18f2cbf204079bb8b7f
