apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: adomate/api
  newName: adomate/api
  newTag: 986abf80ad38f5b86c9b2028c7b5f25ee44de7d7
- name: adomate/dashboard
  newName: adomate/dashboard
  newTag: 1cdeb56c0a583eb00d661f59ecebf42275ab1032
- name: adomate/discord-bot
  newName: adomate/discord-bot
  newTag: a7ee2e3829f9e29fa201ab849033b5f5c7a7495d
- name: adomate/google-ads-controller
  newName: adomate/google-ads-controller
  newTag: f98868a24ed07bd63735c0d5792c55779de2ef33
- name: adomate/mail-server
  newName: adomate/mail-server
  newTag: e051f1ef4140ccad06347dafc12a3b5aec8cdbe3
- name: adomate/site-analyzer
  newName: adomate/site-analyzer
  newTag: eec431f5748a6daada9d7a6817d5ca8763296665
- name: raajpatel229/adomate-frontend
  newName: raajpatel229/adomate-frontend
  newTag: d021b6b9815efc2ab0150a9fb35a8d5a8092fe41
