apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: adomate/api
  newName: adomate/api
  newTag: bbc344f4f0baa75825ae3f49f330d5368b5218ff
- name: adomate/dashboard
  newName: adomate/dashboard
  newTag: 37835e55ca9bf54133080d1ae0964e18650203c7
- name: adomate/discord-bot
  newName: adomate/discord-bot
  newTag: 0951646cb45439dbc3eefbb2ad23777a03300b7a
- name: adomate/google-ads-controller
  newName: adomate/google-ads-controller
  newTag: 8b0ee3b568a86b8dc4e7738361df95e3aeb06a69
- name: adomate/mail-server
  newName: adomate/mail-server
  newTag: e051f1ef4140ccad06347dafc12a3b5aec8cdbe3
- name: adomate/site-analyzer
  newName: adomate/site-analyzer
  newTag: 278f250004f4353e7add483d2a866103519695bb
- name: raajpatel229/adomate-frontend
  newName: raajpatel229/adomate-frontend
  newTag: 59a03a437a79e95002dc0e2b356fa6b9d8721343
