apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: adomate/api
  newName: adomate/api
  newTag: 627b7ba65cea9f7bafccbe17d93bc2f22b25fd71
- name: adomate/dashboard
  newName: adomate/dashboard
  newTag: 257bd750c36652b9dd1bf00248d269a34cb11a9d
- name: adomate/discord-bot
  newName: adomate/discord-bot
  newTag: 19ce2ccc5c55350a0bf60bf7640a09988350d970
- name: adomate/google-ads-controller
  newName: adomate/google-ads-controller
  newTag: f98868a24ed07bd63735c0d5792c55779de2ef33
- name: adomate/mail-server
  newName: adomate/mail-server
  newTag: e051f1ef4140ccad06347dafc12a3b5aec8cdbe3
- name: adomate/site-analyzer
  newName: adomate/site-analyzer
  newTag: eec431f5748a6daada9d7a6817d5ca8763296665
- name: raajpatel229/adomate-frontend
  newName: raajpatel229/adomate-frontend
  newTag: 13630af6b64ed1d435b8772e789cfe7979e904c6
