apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: adomate/api
  newName: adomate/api
  newTag: c87b628abddc346480c56991e50e29d59a296d51
- name: adomate/dashboard
  newName: adomate/dashboard
  newTag: 029aa52541d0f1d5ae6f3ee3f705034e8fb36847
- name: adomate/discord-bot
  newName: adomate/discord-bot
  newTag: 3d699bdd58807258c617e96dca033757f3930493
- name: adomate/google-ads-controller
  newName: adomate/google-ads-controller
  newTag: f98868a24ed07bd63735c0d5792c55779de2ef33
- name: adomate/mail-server
  newName: adomate/mail-server
  newTag: e051f1ef4140ccad06347dafc12a3b5aec8cdbe3
- name: adomate/site-analyzer
  newName: adomate/site-analyzer
  newTag: eec431f5748a6daada9d7a6817d5ca8763296665
- name: raajpatel229/adomate-frontend
  newName: raajpatel229/adomate-frontend
  newTag: 260f04080ba01167deced407e6108ce55ac5e2d3
