apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: adomate/api
  newName: adomate/api
  newTag: 43a85c6ea9445cf93e9d29bc5006d022d15757a4
- name: adomate/dashboard
  newName: adomate/dashboard
  newTag: 37835e55ca9bf54133080d1ae0964e18650203c7
- name: adomate/discord-bot
  newName: adomate/discord-bot
  newTag: 0951646cb45439dbc3eefbb2ad23777a03300b7a
- name: adomate/google-ads-controller
  newName: adomate/google-ads-controller
  newTag: 826531b202dfe4211ab617c38e4009ebcb5c953f
- name: adomate/mail-server
  newName: adomate/mail-server
  newTag: e051f1ef4140ccad06347dafc12a3b5aec8cdbe3
- name: adomate/site-analyzer
  newName: adomate/site-analyzer
  newTag: 278f250004f4353e7add483d2a866103519695bb
- name: raajpatel229/adomate-frontend
  newName: raajpatel229/adomate-frontend
  newTag: cca7fb68fbef2a14361fc01eb40a31ab14a8ac35
