apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../../base
images:
- name: adomate/api
  newName: adomate/api
  newTag: 43a85c6ea9445cf93e9d29bc5006d022d15757a4
- name: adomate/dashboard
  newName: adomate/dashboard
  newTag: 507aa27e507b2357973108c2644531962056a5f0
- name: adomate/discord-bot
  newName: adomate/discord-bot
  newTag: 0951646cb45439dbc3eefbb2ad23777a03300b7a
- name: adomate/google-ads-controller
  newName: adomate/google-ads-controller
  newTag: 23521bd7540757efdd696cfeb542a9e17a92bab7
- name: adomate/mail-server
  newName: adomate/mail-server
  newTag: e051f1ef4140ccad06347dafc12a3b5aec8cdbe3
- name: adomate/site-analyzer
  newName: adomate/site-analyzer
  newTag: 53250ce40448714bb41b46ea114108593222012d
- name: raajpatel229/adomate-frontend
  newName: raajpatel229/adomate-frontend
  newTag: cca7fb68fbef2a14361fc01eb40a31ab14a8ac35
