apiVersion: v1
kind: Service
metadata:
  labels:
    app: discord-bot
  name: discord-bot
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: discord-bot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  namespace: discord-bot
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: discord-bot
  template:
    metadata:
      labels:
        run: discord-bot
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: discord-secrets
        image: adomate/discord-bot:5b608997ea7a67b4d828afc1d291276e84421e74
        imagePullPolicy: Always
        name: api
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 150m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 50Mi
      imagePullSecrets:
      - name: dockerhub-credentials
