apiVersion: v1
kind: Service
metadata:
  labels:
    app: discord-bot
  name: discord-bot
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: discord-bot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: discord-bot
  template:
    metadata:
      labels:
        run: discord-bot
    spec:
      containers:
      - image: adomate/discord-bot:d70956388acb9e9219695cd746c44929c4f44619
        imagePullPolicy: Always
        name: api
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 150m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 50Mi
      imagePullSecrets:
      - name: dockerhub-credentials
