apiVersion: v1
kind: Service
metadata:
  labels:
    app: discord-bot
  name: discord-bot
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: discord-bot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
  namespace: discord-bot
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: discord-bot
  template:
    metadata:
      labels:
        run: discord-bot
    spec:
      containers:
      - env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        envFrom:
        - secretRef:
            name: discord-secrets
        image: adomate/discord-bot:55244dd4c02ef374ba8bbde8ef22b72d9d7efba4
        imagePullPolicy: Always
        name: api
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 150m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 50Mi
      imagePullSecrets:
      - name: dockerhub-credentials
