apiVersion: v1
kind: Service
metadata:
  labels:
    run: api
  name: api
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    run: api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: api
spec:
  replicas: 2
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: api
  template:
    metadata:
      labels:
        run: api
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: api-secrets
        image: adomate/api:519dd59cdfd62b5958e43b8f75b90b68b56b33fc
        imagePullPolicy: Always
        name: api
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
          requests:
            cpu: 200m
            memory: 50Mi
      imagePullSecrets:
      - name: dockerhub-credentials
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  name: api-ingress
  namespace: api
spec:
  rules:
  - host: api.adomate.ai
    http:
      paths:
      - backend:
          service:
            name: api
            port:
              number: 3000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - api.adomate.ai
    secretName: frontend-tls
