apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord-bot
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: discord-bot
  template:
    metadata:
      labels:
        run: discord-bot
    spec:
      containers:
        - name: discord-bot
          image: adomate/discord-bot:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 150m
              memory: 256Mi
          envFrom:
            - secretRef:
                name: discord-secrets
      imagePullSecrets:
        - name: dockerhub-credentials
