apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: adomate/api
  newTag: 7ab4ca39c29f25c82ca409e7418435e88f975686
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
