apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: adomate/api
  newTag: 9e35be1156b7731eaa58907b6462d39a2d824576
resources:
- deployment.yaml
- ingress.yaml
- service.yaml
