apiVersion: v1
kind: Service
metadata:
  labels:
    app: mail-server
  name: mail-server
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: mail-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mail-server
  namespace: mail-server
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      run: mail-server
  template:
    metadata:
      labels:
        run: mail-server
    spec:
      containers:
      - envFrom:
        - secretRef:
            name: mail-server-secrets
        image: adomate/mail-server:49df1be8c5c46862e8060ce25bffaa882908f45b
        imagePullPolicy: Always
        name: mail-server
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: 150m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 50Mi
      imagePullSecrets:
      - name: dockerhub-credentials
